# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    # Install our python package before building the docs
    - method: pip
      path: .


# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/src/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
  - epub