[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "simpm"
authors = [{name = "Project SimPM Team", email = "naima.sadeghi@gmail.com"}]
dynamic = ["version", "description"]